[project]
name = "prompter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "argparse>=1.4.0",
    "groq>=0.13.1",
    "pyperclip>=1.9.0",
    "python-dotenv>=1.0.1",
    "streamlit>=1.41.1",
]
